### ISSUE TITLE
GTK3 File Picker on KDE Plasma

### ISSUE THREAD

**Issue by Alt37** [flathub/org.chromium.Chromium#33] opened 2020-12-06 12:30 UTC
KDE Plasma users naturally prefer native file-picker. Google Chrome &  Chromium packaged by distrubutions both use KDialog (nice middle-ground for now).
Snap and Flatpak versions of Chromium use GTK3 File Picker which comparing to KDialog lacks usabitility feautures & brings interface Inconsistency.

**Comment by Erick555** [comment] 2020-12-06 12:35
AFAIK it's not possible because there is no kde/qt in runtime. The proper solution is to re-enable portal support which will give you native file dialogs but it's currently blocked no upstream regression https://github.com/flatpak/xdg-desktop-portal/issues/545

**Comment by vchernin** [comment] 2021-06-16 19:11
Since https://github.com/flatpak/xdg-desktop-portal/issues/545 should be fixed with [release 1.8.1](https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.8.1), can the xdg-desktop-portal file chooser be [renabled](https://github.com/flathub/org.chromium.Chromium/pull/19#issuecomment-730088310)?

**Comment by vchernin** [comment] 2021-07-02 14:08
@Alt37 Can you test #126

**Comment by refi64** [comment] 2021-09-02 15:51
This should be fixed now as the portal is in upstream Chromium, though we still need `--filesystem=home` due to [this fix](https://github.com/flatpak/xdg-desktop-portal/pull/552) not being in a portal release yet.

**Closed by refi64** 2021-09-02 15:51 UTC

**Comment by PlasmaPower** [comment] 2021-12-29 16:27
The fix linked in the last comment has been merged, and seems to be in all recent releases. I've confirmed locally that file picking seems to work with a `--nofilesystem=home --filesystem=xdg-download --persist=.config/chromium` override. Is there anything else blocking that becoming the default?

**Comment by refi64** [comment] 2021-12-31 21:50
Unfortunately, although the fix is merged:

- xdg-desktop-portal 1.10 isn't widely available (in particular, no stable Ubuntu release has it, and it's not in the PPA)
- Unlike requiring Flatpak 1.8 like we already do, requiring a portal version is hard to check and hard to report to the user in an actionable way
