### ISSUE TITLE
Sync Paused

### ISSUE THREAD

**Issue by gilphilbert** [flathub/org.chromium.Chromium#56] opened 2021-01-21 04:03 UTC
About once a day, my account gets "paused". Once this happens, my passwords aren't synced any longer and any updates to my other accounts aren't synced.

Even after I log in again, the Chromium Password Manager remains empty and my passwords never resync.

What logs can I provide?

**Comment by soaringowl2145** [comment] 2021-01-21 04:20
Not sure if you have seen this but...

https://www.androidpolice.com/2021/01/15/google-cutting-off-chrome-sync-access-to-third-party-chromium-browsers/

**Comment by gilphilbert** [comment] 2021-01-21 04:32
Thanks, I had not.

That's fairly irritating... I guess I'll have to install Chrome to continue syncing with my Google account.

Thanks for the quick response!

**Comment by ggabriel96** [comment] 2021-01-23 03:52
I don't think that's it. The linked article says:

>Google said it would cut third-party browsers' access to Chrome Sync starting on March 15th

Furthermore, I am experiencing this (sync paused) *and* other sites logging out without any reason (like GitHub) in my Flatpak installation of Chromium. Meanwhile, the `dnf` installation is all fine.

**Comment by nedrichards** [comment] 2021-01-23 22:36
The following console errors are printed:

> [2:28:0123/223117.615070:ERROR:token_service_table.cc(140)] Failed to decrypt token for service AccountId-110091813579314459079
[2:76:0123/223120.678448:ERROR:gcm_store_impl.cc(941)] Failed to restore security token.

then after login to google account

> [2:2:0123/223219.274715:ERROR:gaia_auth_fetcher.cc(73)] Missing ID token on refresh token fetch response.
[2:2:0123/223221.041171:ERROR:password_sync_bridge.cc(341)] Passwords datatype error was encountered: Failed to load entries from password store. Encryption service failure.
Failed to load cookie file from cookie: Operation not permitted

That was in both the last version 87 and the current version 88.

**Comment by refi64** [comment] 2021-01-25 02:11
This seems to be related to a similarly weird error in the Chrome Flatpak, though its presence here means it's entirely unrelated to Zypak... I've tried to figure it out before, but unfortunately I can't reproduce it at all...

Could someone who can reproduce this semi-frequently at least run Chromium with `--enable-logging=stderr --v=1` and look for any errors from os_crypt_linux.cc?

**Comment by ggabriel96** [comment] 2021-01-28 00:20
Reinstalled it and ran with those flags. Got a whooole lot of output. Below are a few lines of it.

After turning on sync:

```
[73:14:0127/211002.340345:VERBOSE1:dispatcher.cc(375)] Num tracked contexts: 1
[41:55:0127/211002.354292:VERBOSE1:key_storage_linux.cc(155)] OSCrypt using Libsecret as backend.
[41:55:0127/211002.362575:VERBOSE1:key_storage_libsecret.cc(85)] OSCrypt generated a new password.
[41:55:0127/211002.362649:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
```

After restarting the browser (and then sync was paused):

```
[2:2:0127/211340.811936:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
[2:2:0127/211340.811961:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
[2:2:0127/211340.812004:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
[2:2:0127/211340.812016:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
[2:2:0127/211340.812046:VERBOSE1:chrome_password_manager_client.cc(1221)] ChromePasswordManagerClient: this: 0x351c7b1fa800
[2:2:0127/211340.812057:VERBOSE1:chrome_password_manager_client.cc(1222)] wc: 0x351c7b304200
[2:2:0127/211340.812065:VERBOSE1:chrome_password_manager_client.cc(1223)] wc->GetRenderViewHost(): `0x351c7aa272a0`
[75:9:0127/211340.813324:VERBOSE1:sandbox_linux.cc(70)] Activated seccomp-bpf sandbox for process type: utility.
[41:61:0127/211340.814922:VERBOSE1:network_delegate.cc(32)] NetworkDelegate::NotifyBeforeURLRequest: https://ssl.gstatic.com/safebrowsing/csd/client_model_v5_variation_6.pb
[2:45:0127/211340.817758:VERBOSE1:os_crypt_linux.cc(233)] Decryption failed
[2:45:0127/211340.817787:INFO:login_database.cc(1400)] Password decryption failed, encryption_result is 2
```

The only thing from `os_crypt_linux.cc` are those `Decryption failed`. But there are a lot of them!

**Comment by candrapersada** [comment] 2021-01-28 05:31
From March 15th, Chromium will become Unsynced Chromium

**Comment by refi64** [comment] 2021-01-28 18:59
Okay so for anyone who can indeed reproduce it, can you do the following:

- Install the debug info: `flatpak install org.chromium.Chromium.Debug//stable` (this takes several hundred MBs of disk space)
- Run Chromium normally, make sure the sync is currently broken
- Close Chromium, make sure no processes are left running (you can confirm with `flatpak kill org.chromium.Chromium`)
- Run the following:
  ```
  flatpak run -d --command=gdb org.chromium.Chromium//stable -quiet -batch -ex 'break key_storage_libsecret.cc:108' -ex 'r' -ex 'p password.storage_.value_' -ex 'q' /app/chromium/chrome
  ```
  This will take a while to start but then show quite a bit of output, and towards the end it'll show something like this:
  ```
  Thread 1 "chrome" hit Breakpoint 1, KeyStorageLibsecret::GetKeyImpl (this=<optimized out>) at 
  ../../components/os_crypt/key_storage_libsecret.cc:108
  108	../../components/os_crypt/key_storage_libsecret.cc: No such file or directory.
  $1 = "XXXXXXXXXXXXXXX"
  A debugging session is active.
  ```
  where the `XXXXXXXXXXXXXXX` is your secret. **Do not post this online to this issue tracker!*
- Now, run `secret-tool lookup application chromium`. Is the secret it prints out the same as the secret printed above?

**Comment by ggabriel96** [comment] 2021-01-30 04:13
So I installed the debug info, made sure sync was paused and then that Chromium was not running anymore.
I ran it again with that command and it did take a while to show up. However, it never hit the the breakpoint. Do I have to do anything?

**Comment by cjao** [comment] 2021-02-07 16:49
Could this conceivably be related to #45?

**Comment by ggabriel96** [comment] 2021-02-09 00:08
That would make sense to me. I recall seeing logs about SQLite, but not what they were about. Will check it out.

**Comment by FakeShemp** [comment] 2021-02-18 21:06
For me it doesn't hit the breakpoint either, but worse still is that `secret-tool lookup application chromium` gives me nothing.

**Comment by andrunko** [comment] 2021-03-03 13:28
https://github.com/flathub/org.chromium.Chromium/pull/70 (although not ideal) seems to fix this issue for me, if anyone hitting it could try the PR build it would be great (you may need to relogin one more time and then it should persist).

**Comment by FakeShemp** [comment] 2021-03-03 14:13
> #70 (although not ideal) seems to fix this issue for me, if anyone hitting it could try the PR build it would be great (you may need to relogin one more time and then it should persist).

Yes, this works for me as well.

**Comment by andrunko** [comment] 2021-03-04 15:00
Closing after #70 (manually merged), please reopen if you still hit the issue. Related, see also https://github.com/flatpak/xdg-desktop-portal/issues/557 which may cause chromium to start but fail to load pages.

**Comment by fedelibre** [comment] 2021-05-10 09:16
It doesn't work: I cannot turn on sync in Chromium (version 90.0.4430.93). It's a Google Apps (business) account, in case it matters.

I had to install Chrome from flathub-beta, which works.

**Comment by Erick555** [comment] 2021-05-10 10:58
Google discontinued sync support for third party browsers since 15 March.

**Comment by rayfoss** [comment] 2021-05-10 12:10
> Google discontinued sync support for third party browsers since 15 March.

In practice that's mostly for rebranded versions or maliciously modified ones. Flathub Chromium is working perfectly for me.

**Comment by Erick555** [comment] 2021-05-10 12:30
I don't think they can really differentiate between malicious and non-malicious chromium using their api. Google engineers [made it clear](https://groups.google.com/a/chromium.org/g/chromium-packagers/c/SG6jnsP4pWM) that intent is to drop all third party browsers (non-chrome). For this reason Arch Linux and Fedora dropped sync support themselves. If chromium flatpak still works then I guess google didn't enforced it yet (?) and flatpak is free rider.

**Comment by Erick555** [comment] 2021-05-11 15:07
Various distros went for dropping `google_default_client_id` and `google_default_client_secret` while keeping api key as you described. Note that users can still [workaround sync support themselves](https://gist.github.com/foutrelis/14e339596b89813aa9c37fd1b4e5d9d5).

**Comment by wjt** [comment] 2021-05-12 10:35
I don't know. I opened #106 to get a test build to find out!

**Closed** 2021-05-21 04:23 UTC
