### ISSUE TITLE
Chromium icon instead of webapp icon in Gnome activities overview

### ISSUE THREAD

**Issue by AlbertoFabbri93** [flathub/org.chromium.Chromium#306] opened 2023-08-02 16:31 UTC
Hi, on Gnome if I install a webapp, its icon is shown correctly in the dash but, in the activities overview the Chromium icon is shown instead. See this screenshot:

![Screenshot from 2023-08-02 18-10-54](https://github.com/flathub/org.chromium.Chromium/assets/51910894/23f5ae90-46a1-424f-bc5a-29e105d11217)

The icon circled in red should be the YouTube logo (it is the YouTube webapp). Notice how in the dash the icon is correct.

**Comment by wjt** [comment] 2023-08-02 16:35
Duplicate of #216.

Notice that in the dash in your screenshot, there is no dot under the youtube icon.

**Closed by wjt** 2023-08-02 16:35 UTC
